// Mock Data & Translations for NaviGo MVP

const translations = {
    en: {
        hero_title: "Find the right government service in seconds.",
        hero_subtitle: "NaviGo replaces confusion with clear action. We help you discover, understand, and apply for government schemes with step-by-step guidance.",
        nav_dashboard: "My Dashboard",
        btn_start_journey: "Start Your Journey",
        feat_eligibility_title: "Eligibility & Documents",
        feat_eligibility_desc: "Get instant eligibility checks and personalized document checklists.",
        feat_language_title: "In Your Language",
        feat_language_desc: "Ask questions in English, Hindi, Kannada, or Telugu.",
        feat_plans_title: "Clear Action Plans",
        feat_plans_desc: "Turn bureaucratic confusion into a simple, step-by-step roadmap.",
        db_title: "How can we help you today?",
        db_subtitle: "Describe your goal in your own words.",
        db_input_placeholder: "E.g., I want to start a food business...",
        db_common_goals: "Common Citizen Goals",
        db_food_title: "Start a Food Business",
        db_food_subtitle: "FSSAI Registration & Licensing",
        db_farm_title: "Farming Support",
        db_farm_subtitle: "PM-KISAN Subsidy",
        db_scholarship_title: "Student Scholarships",
        db_scholarship_subtitle: "National Scholarship Portal",
        db_business_title: "Register My Business",
        db_business_subtitle: "Udyam (MSME) Registration",
        db_active_journeys: "Your Active Journeys",
        db_active_journeys_sub: "Resume where you left off",
        wiz_cancel: "Cancel Journey",
        wiz_step_service: "Service",
        wiz_step_eligibility: "Eligibility",
        wiz_step_documents: "Documents",
        wiz_step_plan: "Plan",
        wiz_step_analyze: "Analyze",
        wiz_proceed_eligibility: "Proceed to Eligibility",
        wiz_elig_title: "Am I Eligible?",
        wiz_elig_subtitle: "Here are the criteria you need to meet for this service.",
        btn_back: "Back",
        wiz_meet_criteria: "I Meet These Criteria",
        wiz_docs_title: "Required Documents",
        wiz_docs_subtitle: "Gather these documents before you start the application.",
        wiz_view_plan: "View Action Plan",
        wiz_plan_title: "Your Action Plan",
        wiz_next_analyze: "Next: Analyze Documents",
        wiz_upload_title: "AI Document Check",
        wiz_upload_subtitle: "Have a rejection letter or blurry document? Upload it to let AI verify it before you apply.",
        wiz_upload_click: "Click to upload",
        wiz_upload_formats: "Supports PDF, PNG, JPG",
        wiz_complete: "Save Journey & Finish",
        track_back: "Back to Dashboard",
        track_title: "My Active Journeys",
        track_subtitle: "Track your progress and pick up right where you left off.",
        track_empty: "No saved journeys yet."
    },
    hi: {
        hero_title: "सेकंडों में सही सरकारी सेवा खोजें।",
        hero_subtitle: "नेविगो भ्रम को स्पष्ट कार्रवाई से बदल देता है। हम चरण-दर-चरण मार्गदर्शन के साथ सरकारी योजनाओं को खोजने, समझने और आवेदन करने में आपकी सहायता करते हैं।",
        nav_dashboard: "मेरा डैशबोर्ड",
        btn_start_journey: "अपनी यात्रा शुरू करें",
        feat_eligibility_title: "पात्रता और दस्तावेज़",
        feat_eligibility_desc: "त्वरित पात्रता जांच और व्यक्तिगत दस्तावेज़ चेकलिस्ट प्राप्त करें।",
        feat_language_title: "आपकी भाषा में",
        feat_language_desc: "अंग्रेजी, हिंदी, कन्नड़ या तेलुगु में प्रश्न पूछें।",
        feat_plans_title: "स्पष्ट कार्य योजनाएं",
        feat_plans_desc: "नौकरशाही के भ्रम को एक सरल, चरण-दर-चरण रोडमैप में बदलें।",
        db_title: "आज हम आपकी क्या सहायता कर सकते हैं?",
        db_subtitle: "अपने शब्दों में अपना लक्ष्य बताएं।",
        db_input_placeholder: "जैसे, मैं खाद्य व्यवसाय शुरू करना चाहता हूँ...",
        db_common_goals: "सामान्य नागरिक लक्ष्य",
        db_food_title: "खाद्य व्यवसाय शुरू करें",
        db_food_subtitle: "FSSAI पंजीकरण और लाइसेंसिंग",
        db_farm_title: "खेती सहायता",
        db_farm_subtitle: "पीएम-किसान सब्सिडी",
        db_scholarship_title: "छात्र छात्रवृत्ति",
        db_scholarship_subtitle: "राष्ट्रीय छात्रवृत्ति पोर्टल",
        db_business_title: "मेरा व्यवसाय पंजीकृत करें",
        db_business_subtitle: "उद्यम (MSME) पंजीकरण",
        db_active_journeys: "आपकी सक्रिय यात्राएँ",
        db_active_journeys_sub: "वहीं से शुरू करें जहां आपने छोड़ा था",
        wiz_cancel: "यात्रा रद्द करें",
        wiz_step_service: "सेवा",
        wiz_step_eligibility: "पात्रता",
        wiz_step_documents: "दस्तावेज़",
        wiz_step_plan: "योजना",
        wiz_step_analyze: "विश्लेषण",
        wiz_proceed_eligibility: "पात्रता पर आगे बढ़ें",
        wiz_elig_title: "क्या मैं पात्र हूँ?",
        wiz_elig_subtitle: "यहाँ वे मानदंड दिए गए हैं जिन्हें आपको इस सेवा के लिए पूरा करना होगा।",
        btn_back: "पीछे",
        wiz_meet_criteria: "मैं इन मानदंडों को पूरा करता हूँ",
        wiz_docs_title: "आवश्यक दस्तावेज़",
        wiz_docs_subtitle: "आवेदन शुरू करने से पहले ये दस्तावेज़ एकत्र करें।",
        wiz_view_plan: "कार्य योजना देखें",
        wiz_plan_title: "आपकी कार्य योजना",
        wiz_next_analyze: "अगला: दस्तावेज़ों का विश्लेषण करें",
        wiz_upload_title: "एआई दस्तावेज़ जांच",
        wiz_upload_subtitle: "अस्वीकृति पत्र या धुंधला दस्तावेज़ है? आवेदन करने से पहले एआई से सत्यापित कराने के लिए इसे अपलोड करें।",
        wiz_upload_click: "अपलोड करने के लिए क्लिक करें",
        wiz_upload_formats: "PDF, PNG, JPG समर्थित",
        wiz_complete: "यात्रा सहेजें और समाप्त करें",
        track_back: "डैशबोर्ड पर वापस जाएं",
        track_title: "मेरी सक्रिय यात्राएँ",
        track_subtitle: "अपनी प्रगति को ट्रैक करें और वहीं से शुरू करें जहां आपने छोड़ा था।",
        track_empty: "अभी तक कोई सहेजी गई यात्रा नहीं है।"
    },
    kn: {
        hero_title: "ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಸರಿಯಾದ ಸರ್ಕಾರಿ ಸೇವೆಯನ್ನು ಹುಡುಕಿ.",
        hero_subtitle: "ನವಿಗೊ ಗೊಂದಲವನ್ನು ಸ್ಪಷ್ಟ ಕ್ರಿಯೆಯೊಂದಿಗೆ ಬದಲಾಯಿಸುತ್ತದೆ. ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಲು, ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಮತ್ತು ಹಂತ-ಹಂತದ ಮಾರ್ಗದರ್ಶನದೊಂದಿಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಲು ನಾವು ನಿಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತೇವೆ.",
        nav_dashboard: "ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        btn_start_journey: "ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
        feat_eligibility_title: "ಅರ್ಹತೆ ಮತ್ತು ದಾಖಲೆಗಳು",
        feat_eligibility_desc: "ತ್ವರಿತ ಅರ್ಹತೆಯ ಪರಿಶೀಲನೆಗಳು ಮತ್ತು ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ದಾಖಲೆಗಳ ಪರಿಶೀಲನಾಪಟ್ಟಿ ಪಡೆಯಿರಿ.",
        feat_language_title: "ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ",
        feat_language_desc: "ಇಂಗ್ಲಿಷ್, ಹಿಂದಿ, ಕನ್ನಡ ಅಥವಾ ತೆಲುಗಿನಲ್ಲಿ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಿ.",
        feat_plans_title: "ಸ್ಪಷ್ಟ ಕ್ರಿಯಾ ಯೋಜನೆಗಳು",
        feat_plans_desc: "ಅಧಿಕಾರಶಾಹಿ ಗೊಂದಲವನ್ನು ಸರಳ, ಹಂತ-ಹಂತದ ಮಾರ್ಗಸೂಚಿಯಾಗಿ ಪರಿವರ್ತಿಸಿ.",
        db_title: "ಇಂದು ನಾವು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?",
        db_subtitle: "ನಿಮ್ಮ ಸ್ವಂತ ಮಾತುಗಳಲ್ಲಿ ನಿಮ್ಮ ಗುರಿಯನ್ನು ವಿವರಿಸಿ.",
        db_input_placeholder: "ಉದಾಹರಣೆಗೆ, ನಾನು ಆಹಾರ ವ್ಯವಹಾರವನ್ನು ಪ್ರಾರಂಭಿಸಲು ಬಯಸುತ್ತೇನೆ...",
        db_common_goals: "ಸಾಮಾನ್ಯ ನಾಗರಿಕ ಗುರಿಗಳು",
        db_food_title: "ಆಹಾರ ವ್ಯವಹಾರ ಪ್ರಾರಂಭಿಸಿ",
        db_food_subtitle: "FSSAI ನೋಂದಣಿ ಮತ್ತು ಪರವానಗಿ",
        db_farm_title: "ಕೃಷಿ ನೆರವು",
        db_farm_subtitle: "ಪಿಎಂ-ಕಿಸಾನ್ ಸಹಾಯಧನ",
        db_scholarship_title: "ವಿದ್ಯಾರ್ಥಿ ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು",
        db_scholarship_subtitle: "ರಾಷ್ಟ್ರೀಯ ವಿದ್ಯಾರ್ಥಿವೇತನ ಪೋರ್ಟಲ್",
        db_business_title: "ನನ್ನ ವ್ಯವಹಾರವನ್ನು ನೋಂದಾಯಿಸಿ",
        db_business_subtitle: "ಉದ್ಯಮ (MSME) ನೋಂದಣಿ",
        db_active_journeys: "ನಿಮ್ಮ ಸಕ್ರಿಯ ಪ್ರಯಾಣಗಳು",
        db_active_journeys_sub: "ನೀವು ನಿಲ್ಲಿಸಿದ ಸ್ಥಳದಿಂದ ಪುನರಾರಂಭಿಸಿ",
        wiz_cancel: "ಪ್ರಯಾಣ ರದ್ದುಗೊಳಿಸಿ",
        wiz_step_service: "ಸೇವೆ",
        wiz_step_eligibility: "ಅರ್ಹತೆ",
        wiz_step_documents: "ದಾಖಲೆಗಳು",
        wiz_step_plan: "ಯೋಜನೆ",
        wiz_step_analyze: "ವಿಶ್ಲೇಷಿಸಿ",
        wiz_proceed_eligibility: "ಅರ್ಹತೆಗೆ ಮುಂದುವರಿಯಿರಿ",
        wiz_elig_title: "ನಾನು ಅರ್ಹನೇ?",
        wiz_elig_subtitle: "ಈ ಸೇವೆಗಾಗಿ ನೀವು ಪೂರೈಸಬೇಕಾದ ಮಾನದಂಡಗಳು ಇಲ್ಲಿವೆ.",
        btn_back: "ಹಿಂದಕ್ಕೆ",
        wiz_meet_criteria: "ನಾನು ಈ ಮಾನದಂಡಗಳನ್ನು ಪೂರೈಸುತ್ತೇನೆ",
        wiz_docs_title: "ಅಗತ್ಯವಿರುವ ದಾಖಲೆಗಳು",
        wiz_docs_subtitle: "ಅರ್ಜಿ ಸಲ್ಲಿಸುವ ಮುನ್ನ ಈ ದಾಖಲೆಗಳನ್ನು ಸಂಗ್ರಹಿಸಿ.",
        wiz_view_plan: "ಕ್ರಿಯಾ ಯೋಜನೆ ವೀಕ್ಷಿಸಿ",
        wiz_plan_title: "ನಿಮ್ಮ ಕ್ರಿಯಾ ಯೋಜನೆ",
        wiz_next_analyze: "ಮುಂದೆ: ದಾಖಲೆಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ",
        wiz_upload_title: "AI ದಾಖಲೆ ಪರಿಶೀಲನೆ",
        wiz_upload_subtitle: "ತಿರಸ್ಕಾರ ಪತ್ರ ಅಥವಾ ಅಸ್ಪಷ್ಟ ದಾಖಲೆ ಇದೆಯೇ? ಅರ್ಜಿ ಸಲ್ಲಿಸುವ ಮುನ್ನ AI ಪರಿಶೀಲಿಸಲು ಅದನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
        wiz_upload_click: "ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
        wiz_upload_formats: "PDF, PNG, JPG ಬೆಂಬಲಿಸುತ್ತದೆ",
        wiz_complete: "ಪ್ರಯಾಣ ಉಳಿಸಿ ಮತ್ತು ಮುಗಿಸಿ",
        track_back: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ",
        track_title: "ನನ್ನ ಸಕ್ರಿಯ ಪ್ರಯಾಣಗಳು",
        track_subtitle: "ನಿಮ್ಮ ಪ್ರಗತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ನೀವು ನಿಲ್ಲಿಸಿದ ಸ್ಥಳದಿಂದ ಪ್ರಾರಂಭಿಸಿ.",
        track_empty: "ಇನ್ನೂ ಯಾವುದೇ ಉಳಿಸಿದ ಪ್ರಯಾಣಗಳಿಲ್ಲ."
    },
    te: {
        hero_title: "సెకన్లలో సరైన ప్రభుత్వ సేవను కనుగొనండి.",
        hero_subtitle: "నవిగో గందరగోళాన్ని స్పష్టమైన చర్యతో భర్తీ చేస్తుంది. దశలవారీ మార్గదర్శకత్వంతో ప్రభుత్వ పథకాలను కనుగొనడం, అర్థం చేసుకోవడం మరియు దరఖాస్తు చేయడంలో మేము మీకు సహాయం చేస్తాము.",
        nav_dashboard: "నా డాష్‌బోర్డ్",
        btn_start_journey: "మీ ప్రయాణాన్ని ప్రారంభించండి",
        feat_eligibility_title: "అర్హత & పత్రాలు",
        feat_eligibility_desc: "తక్షణ అర్హత తనిఖీలు మరియు వ్యక్తిగతీకరించిన పత్రాల చెక్‌లిస్ట్ పొందండి.",
        feat_language_title: "మీ భాషలో",
        feat_language_desc: "ఇంగ్లీష్, హిందీ, కన్నడ లేదా తెలుగులో ప్రశ్నలు అడగండి.",
        feat_plans_title: "స్పష్టమైన కార్యాచరణ ప్రణాళికలు",
        feat_plans_desc: "అధికారిక గందరగోళాన్ని సరళమైన, దశల వారీ రోడ్‌మ్యాప్‌గా మార్చండి.",
        db_title: "ఈ రోజు మేము మీకు ఎలా సహాయపడగలము?",
        db_subtitle: "మీ స్వంత మాటలలో మీ లక్ష్యాన్ని వివరించండి.",
        db_input_placeholder: "ఉదాహరణకు, నేను ఆహార వ్యాపారాన్ని ప్రారంభించాలనుకుంటున్నాను...",
        db_common_goals: "సాధారణ పౌర లక్ష్యాలు",
        db_food_title: "ఆహార వ్యాపారాన్ని ప్రారంభించండి",
        db_food_subtitle: "FSSAI రిజిస్ట్రేషన్ & లైసెన్సింగ్",
        db_farm_title: "వ్యవసాయ మద్దతు",
        db_farm_subtitle: "పీఎం-కిసాన్ సబ్సిడీ",
        db_scholarship_title: "విద్యార్థి స్కాలర్‌షిప్‌లు",
        db_scholarship_subtitle: "నేషనల్ స్కాలర్‌షిప్ పోర్టల్",
        db_business_title: "నా వ్యాపారాన్ని నమోదు చేయండి",
        db_business_subtitle: "ఉద్యమ (MSME) రిజిస్ట్రేషన్",
        db_active_journeys: "మీ క్రియాశీల ప్రయాణాలు",
        db_active_journeys_sub: "మీరు ఎక్కడ ఆపివేశారో అక్కడ నుండి పునఃప్రారంభించండి",
        wiz_cancel: "ప్రయాణాన్ని రద్దు చేయి",
        wiz_step_service: "సేవ",
        wiz_step_eligibility: "అర్హత",
        wiz_step_documents: "పత్రాలు",
        wiz_step_plan: "ప్రణాళిక",
        wiz_step_analyze: "విశ్లేషించు",
        wiz_proceed_eligibility: "అర్హతకు వెళ్లండి",
        wiz_elig_title: "నేను అర్హుడినేనా?",
        wiz_elig_subtitle: "ఈ సేవ కోసం మీరు పూర్తి చేయాల్సిన ప్రమాణాలు ఇక్కడ ఉన్నాయి.",
        btn_back: "వెనుకకు",
        wiz_meet_criteria: "నేను ఈ ప్రమాణాలను పూర్తి చేస్తాను",
        wiz_docs_title: "అవసరమైన పత్రాలు",
        wiz_docs_subtitle: "దరఖాస్తు ప్రారంభించడానికి ముందు ఈ పత్రాలను సేకరించండి.",
        wiz_view_plan: "కార్యాచరణ ప్రణాళికను వీక్షించండి",
        wiz_plan_title: "మీ కార్యాచరణ ప్రణాళిక",
        wiz_next_analyze: "తరువాత: పత్రాలను విశ్లేషించండి",
        wiz_upload_title: "AI పత్రాల తనిఖీ",
        wiz_upload_subtitle: "తిరస్కరణ పత్రం లేదా అస్పష్టమైన పత్రం ఉందా? దరఖాస్తు చేయడానికి ముందు AI చేత ధృవీకరించడానికి దాన్ని అప్‌లోడ్ చేయండి.",
        wiz_upload_click: "అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి",
        wiz_upload_formats: "PDF, PNG, JPG లకు మద్దతు ఇస్తుంది",
        wiz_complete: "ప్రయాణాన్ని సేవ్ చేసి ముగించండి",
        track_back: "డాష్‌బోర్డ్‌కు తిరిగి వెళ్లండి",
        track_title: "నా క్రియాశీల ప్రయాణాలు",
        track_subtitle: "మీ పురోగతిని ట్రాక్ చేయండి మరియు మీరు ఎక్కడ ఆపివేశారో అక్కడ నుండి ప్రారంభించండి.",
        track_empty: "ఇంకా సేవ్ చేసిన ప్రయాణాలు లేవు."
    }
};

const serviceData = {
    fssai: {
        id: "fssai",
        title: "FSSAI Registration & Licensing",
        desc: "Official registration for all food-related businesses in India.",
        match: "High Match - Food Business Intent Detected",
        eligibility: [
            "Any person handling food manufacturing, processing, or sales.",
            "Petty food business operators (turnover below ₹12 Lakhs) need Basic Registration.",
            "Turnover above ₹12 Lakhs requires a State or Central License."
        ],
        documents: [
            { id: "f1", name: "Photo ID Proof", desc: "Aadhaar / PAN / Voter ID. Must be clearly visible." },
            { id: "f2", name: "Passport Size Photograph", desc: "Recent color photo." },
            { id: "f3", name: "Proof of Premises", desc: "Rent agreement, Electricity bill, or NOC from owner." }
        ],
        timeline: [
            "Compile your ID, Photo, and Premise proof.",
            "Visit the official FoSCoS portal (foscos.fssai.gov.in).",
            "Select 'Apply for License/Registration' and fill Form A/B.",
            "Pay the fee (₹100 for Basic Registration) and submit."
        ],
        mistakes: [
            "Uploading an electricity bill that has a different name than the applicant.",
            "Paying higher fees to fraudulent third-party agents."
        ]
    },
    pmkisan: {
        id: "pmkisan",
        title: "PM-KISAN Samman Nidhi",
        desc: "Income support of ₹6,000 per year to all land-holding farmer families.",
        match: "High Match - Farming Intent Detected",
        eligibility: [
            "Must be a land-holding farmer family.",
            "Cultivable land must be registered in your name.",
            "Must not be an institutional landholder, current/former minister, or paying income tax."
        ],
        documents: [
            { id: "p1", name: "Aadhaar Card", desc: "Mandatory for e-KYC." },
            { id: "p2", name: "Land Ownership Documents", desc: "Khatauni / Patta." },
            { id: "p3", name: "Bank Account Details", desc: "Aadhaar-seeded active bank account." }
        ],
        timeline: [
            "Keep your Aadhaar and Land documents ready.",
            "Visit pmkisan.gov.in and click on 'New Farmer Registration'.",
            "Complete OTP-based e-KYC using your Aadhaar linked mobile.",
            "Submit land details and await verification from local Patwari."
        ],
        mistakes: [
            "Bank account is not Aadhaar-seeded (payment will fail).",
            "Name on Aadhaar does not exactly match name on land records."
        ]
    },
    nsp: {
        id: "nsp",
        title: "National Scholarship Portal (NSP)",
        desc: "One-stop platform for all government scholarships for students.",
        match: "High Match - Student Intent Detected",
        eligibility: [
            "Must be a citizen of India.",
            "Must be enrolled in a recognized educational institution.",
            "Income and academic merit thresholds vary by specific scheme."
        ],
        documents: [
            { id: "n1", name: "Aadhaar Card", desc: "Linked to mobile and bank." },
            { id: "n2", name: "Previous Year Marksheet", desc: "Proof of academic progression." },
            { id: "n3", name: "Income / Caste Certificate", desc: "Issued by competent authority (if applicable)." }
        ],
        timeline: [
            "Register on scholarships.gov.in using your Aadhaar.",
            "Log in and fill the common application form.",
            "Upload scanned copies of required documents.",
            "Submit before the deadline to your institute for verification."
        ],
        mistakes: [
            "Uploading unverified photocopies instead of original scanned copies.",
            "Missing the institute-level verification deadline."
        ]
    },
    udyam: {
        id: "udyam",
        title: "Udyam (MSME) Registration",
        desc: "Zero-cost government registration for Micro, Small, and Medium Enterprises.",
        match: "High Match - Business Intent Detected",
        eligibility: [
            "Any individual intending to establish a micro, small or medium enterprise.",
            "Based entirely on self-declaration of investment and turnover."
        ],
        documents: [
            { id: "u1", name: "Aadhaar Card", desc: "Must be linked to mobile number for OTP validation." },
            { id: "u2", name: "PAN Card", desc: "Business or Individual PAN." },
            { id: "u3", name: "Bank Account Details", desc: "Account number and IFSC code." }
        ],
        timeline: [
            "Visit udyamregistration.gov.in (Official free portal).",
            "Enter Aadhaar number and verify via OTP.",
            "Fill in PAN details to auto-fetch tax data.",
            "Provide business address and activity details, then submit."
        ],
        mistakes: [
            "Paying registration fees (Udyam is strictly a FREE government service).",
            "Not having a mobile number linked to your Aadhaar card."
        ]
    }
};

let savedJourneys = [];
